// LIVE-ONLY script: todo 6 integration loop against the real wiki.js instance
// (localhost:3000). Writes ONLY under _sandbox/qa06-<timestamp>/ and deletes
// everything it creates. Never run in CI; unit tests use mocks.
//
//   node test/live/loop06.mjs
//
// Reads dist/ output — run `npm run build` first.

import { homedir } from 'node:os';
import { resolveOptions } from '../../dist/config.js';
import { createClient, gql } from '../../dist/wiki/client.js';
import { readPage, createPage, updatePage, appendSection, deletePage } from '../../dist/wiki/pages.js';

const options = resolveOptions({});
const deps = { client: createClient(options, { homeDir: homedir() }), options };

const ts = new Date().toISOString().replace(/[:.]/g, '-');
const path = `_sandbox/qa06-${ts}/pitfall-run`;
const url = options.baseUrl;

function line(label, value) {
  console.log(`[${label}] ${typeof value === 'string' ? value : JSON.stringify(value)}`);
}

async function rawRead(fields) {
  const query = `query { pages { singleByPath(path: "${path}", locale: "en") { ${fields} } } }`;
  return gql(deps.client, query, {});
}

let created = false;
try {
  // 1. create (twin:false, isPublished:true — twin skipped by design)
  const createdResult = await createPage(deps, {
    path,
    locale: 'en',
    title: 'QA06 Loop Page',
    content: '# QA06 Loop\nGenerated by todo 6 live loop.',
    isPublished: true,
    twin: false,
  });
  created = true;
  line('STEP1 create result', createdResult);

  // 2. readPage — content must match what we wrote
  const read1 = await readPage(deps.client, path, 'en');
  if (read1 === null) throw new Error('readPage returned null right after create');
  if (!read1.content.includes('Generated by todo 6 live loop.')) {
    throw new Error(`content mismatch after create: ${read1.content}`);
  }
  line('STEP2 readPage after create', { id: read1.id, title: read1.title, isPublished: read1.isPublished, contentHead: read1.content.split('\n')[0] });

  // 3. appendSection — read must show the appended tail
  const appended = await appendSection(deps, path, 'en', '## QA06 Tail Section');
  const read2 = await readPage(deps.client, path, 'en');
  if (read2 === null || !read2.content.endsWith('## QA06 Tail Section')) {
    throw new Error(`append section not visible after appendSection: ${read2?.content}`);
  }
  line('STEP3 appendSection', { pageId: appended.pageId, contentTail: read2.content.split('\n').slice(-1)[0] });

  // 4. update full-writeback, first pass: set publishStartDate + scriptCss
  const updated1 = await updatePage(deps, read1.id, {
    title: 'QA06 Renamed',
    publishStartDate: '2026-09-01T00:00:00.000Z',
    scriptCss: 'h1{color:red}',
  });
  line('STEP4 update with publish+script', { pageId: updated1.pageId, title: updated1.page.title });

  // 5. update AGAIN with ONLY a title patch — pitfall #1: the payload must
  //    still carry publishStartDate + scriptCss from the read
  const updated2 = await updatePage(deps, read1.id, { title: 'QA06 Renamed Twice' });
  line('STEP5 update title-only', { pageId: updated2.pageId, title: updated2.page.title });

  // 6. RAW GraphQL re-read proves the omitted fields were NOT wiped
  const raw = await rawRead('title publishStartDate scriptCss');
  line('STEP6 raw graphql re-read', raw.pages.singleByPath);

  // 7. anonymous HTTP: en published 200 expected; zh twin does not exist
  const enStatus = await fetch(`${url}/en/${path}`).then((r) => r.status).catch((e) => `err:${e.message}`);
  const zhStatus = await fetch(`${url}/zh/${path}`).then((r) => r.status).catch((e) => `err:${e.message}`);
  line('STEP7 anonymous HTTP', { en: enStatus, zh: zhStatus });
  if (enStatus !== 200) throw new Error(`expected 200 for /en/${path}, got ${enStatus}`);
  // twin skipped (twin:false) — /zh must NOT be 200
  if (zhStatus === 200) throw new Error(`unexpected 200 for /zh/${path} (twin should not exist)`);

  // 8. deletePage — readPage must be null afterwards
  const deleted = await deletePage(deps, path, 'en', 'yes');
  line('STEP8 delete', deleted);
  const read3 = await readPage(deps.client, path, 'en');
  if (read3 !== null) throw new Error('readPage not null after delete');
  line('STEP9 readPage after delete', 'null (page gone)');
  console.log('LOOP06 OK');
} catch (err) {
  console.error(`LOOP06 FAILED: ${err.message}`);
  if (created) {
    try {
      const deleted = await deletePage(deps, path, 'en', 'yes');
      console.error(`cleanup delete: ${JSON.stringify(deleted)}`);
    } catch (cleanupErr) {
      console.error(`cleanup failed: ${cleanupErr.message}`);
    }
  }
  process.exitCode = 1;
}